# Netlify設定ファイル - shift48.com

# ビルド設定
[build]
  # ビルドコマンドを元に戻す
  command = "npm run build"
  # 公開ディレクトリ
  publish = "_site"
  # 機能フラグ
  functions = "netlify/functions"

# 環境変数
[build.environment]
  NODE_VERSION = "18"

# リダイレクト設定
[[redirects]]
  # 404ページへのリダイレクト
  from = "/*"
  to = "/404.html"
  status = 404

# ヘッダー設定
[[headers]]
  # すべてのページに適用
  for = "/*"
    [headers.values]
    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://pagead2.googlesyndication.com https://www.googletagmanager.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; frame-src 'self' https://www.youtube.com https://platform.twitter.com;"

# プラグイン設定（コメントアウトを解除）
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "lighthouse-results"
    [plugins.inputs.thresholds]
      accessibility = 0